language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: idiJAE7qRKgSUXp24l8K/sc2/DVHT0E8c4OIVnNLRuL3J3VKCmekbDk3/Mr9TicLtUwAEfoxvSatWhg91Ag4as5hTh9U/W9nUIVNpV7CCA6TlpZY0TTLq3lgTG8bhw6WbaeXLb8IYJskplOPL2uStmijV8cQG1Q5JUCMGS8NQOxo7aHvQ3MNjT6lf92dT+lVJXEqQ5X6SGZG0e8qO5mIQDZVDUHDU9wj+SkyE3vYEP49fIcjq1In4kmYa5PGb8+DDovUYwKNva36M/tPXJ4hjw5Y1FZsvyHBTRgt1Lwh1Q5asQHsVVwgug0xHamvn9v3FD1LDQjeSP//nfl2O8pLKg5f13LDSfLwDU9qyyYql56KCk2+pHwd21wQfz5/fHhuU/ROgxKKs5DV3x+4mRKnKZmrhjwEIersjxtPiZa3F8QUwXex3E3wevlsjnjf2PeDWHuw3F9qNyNKcODP4ldlNha6AVywArfI0Cok2yl2hZYbq5d82oddwjsVuYHk/RlO6oE7emD9j+RmyggWwB7agtYDWzCNqiSU+cGa0gCAB9+VzMvN2JNFeViy0vYuWI1ZyJXurCsB+GUgEt2L+msJ9JcfMNhXFYUXcsKr+UtI4UaGUxQnfiq2k4eK4UeyEeqpeaNYssD6N++CmuWu/KNm86wUke7esBdgjgh3WNsoWmA=
  app: pacific-earth-38644
  on:
    repo: preetha5/node_blog_api
