language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Dv/2ka7XpsJqXxm6BuSuM8L2X7wJITznWCRHwa08w/ThXzuAIiEsntwsFSQ79xSt/GHxm7JGUYh2bAbfNvMrKSCBXZWss4gxyZZ0D7uLgzAkEjmGg9LrdXXewU3Rh3qch3/D0zKBbpoidW1C7zxWS8XBB/7+ySdJlXQe3InuENN3UvGBjprhn1R/xaQRdOI5THxbDoOp2qLify4TxGRqw9MY0Q19s5rgS4EISDHuQVxEyvqdrWXpksZwdIFiUVL2rRX1p2qdFkuf0wx2xrCiyut6RZ5Hjv4PvCY0VNzGKQU1fhB1+yHxjnISAcPKkqDackMKzdq50DzmhWkS9H//5kDCO5Pe+kU8ua/6DW1UfzlruZMs0iNUv16OB4LtkrJP9g4kB0EOVBHPhcRe+lITYSlk9M/GVKri81eEj1Zd4rLdeVtH9lZpGdvUcf0AoOT/sNlyAOAOBRTSX0RxTSke+mRLDZKQbxRZSES6/7xQtpKXBJxQJ+gT5cZzoLbNyfQxBvNPvmCu/Q21gWifHeWbEgt2wdMcQigtvInp1o0rh3ES9CLhEO0E1btRLQSgV6FkL2M8k2jboWTWcgVV69Yx1SIDIGk/51cU/akgd6kS00ynwV+6kDwqIj95pRW8PU70CVVLMAka3QxpLuT4aqilfETbw6ZzjbRJVdhf2rB9Scc=
  app: pacific-earth-38644
  on:
    repo: preetha5/node_blog_api
